import type { Metadata } from 'next'
import { Bungee_Outline, Bungee_Shade, Gugi } from 'next/font/google'
import '@/styles/globals.scss'
import { Providers } from '../../providers/providers'
import Header from '@/components/Header/Header'
import { EnHeaderType } from '@/components/Header/Header.types'

const bungeeOutline = Bungee_Outline({
	variable: '--font-bungee-outline',
	weight: '400',
	subsets: ['latin'],
})

const bungeeShade = Bungee_Shade({
	variable: '--font-bungee-shade',
	weight: '400',
	subsets: ['latin'],
})

const gugi = Gugi({
	variable: '--font-gugi-sans',
	weight: '400',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={` ${bungeeOutline.variable}  ${bungeeShade.variable}  ${gugi.variable}  `}
			>
				<Providers>
					<Header type={EnHeaderType.Main} />
					{children}
				</Providers>
			</body>
		</html>
	)
}
