import Header from '@/components/Header/Header'
import { Providers } from '@/providers/providers'
import '@/styles/globals.scss'

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<Header />
			<body>
				<Providers>{children}</Providers>
			</body>
		</html>
	)
}
